server {
    listen 80;
    listen [::]:80;
    server_name fen.cosmolex.ru;

    root /var/www/fen.cosmolex.ru/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location = /robots.txt {
        access_log off;
        log_not_found off;
    }

    location = /favicon.svg {
        access_log off;
        log_not_found off;
    }

    location ~* \.(?:css|js|mjs|map|jpg|jpeg|gif|png|svg|ico|webp|mp4|woff2?)$ {
        expires 30d;
        access_log off;
        add_header Cache-Control "public, immutable";
    }
}
